const USER_STATE_KEY='vancouver-rentals:user-state:v1';
const state={listings:[],history:{},user:JSON.parse(localStorage.getItem(USER_STATE_KEY)||'{}'),markers:new Map(),map:null};
const $=id=>document.getElementById(id);
const money=n=>n==null?'—':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(n);
const boolLabel=(v,yes,no='No')=>v===true?yes:v===false?no:'Unknown';
function saveUser(){localStorage.setItem(USER_STATE_KEY,JSON.stringify(state.user));}
function userFor(id){return state.user[id]||(state.user[id]={favorite:false,hidden:false,contacted:false,notes:''});}
function score(l){let s=0,reasons=[];if(l.sqft>=800){s+=18;reasons.push('800+ sqft')}if(l.bedrooms>=2){s+=15;reasons.push('2BR+')}if(l.bathrooms>=2)s+=8;if(l.ac===true){s+=16;reasons.push('AC')}else if(l.ac===false)s-=10;if(l.buildingYear>=2020){s+=12;reasons.push('newer building')}else if(l.buildingYear>=2015)s+=7;const o=(l.orientation||'').toLowerCase();if(['s','south','se','southeast','sw','southwest'].includes(o)){s+=12;reasons.push('preferred exposure')}if(['n','north'].includes(o)){s-=18;reasons.push('north-facing')}if(l.parking===true){s+=7;reasons.push('parking')}if(l.largeWindows===true){s+=6;reasons.push('large windows')}if(l.modernInterior===true){s+=6;reasons.push('modern interior')}if(l.type==='purpose-built')s+=3;return {value:Math.max(0,Math.min(100,Math.round(s))),reasons};}
function filtered(){const minSqft=+$('minSqft').value||0,beds=+$('beds').value||0,baths=+$('baths').value||0,minPrice=+$('minPrice').value||0,maxPrice=+$('maxPrice').value||Infinity,minYear=+$('minYear').value||0;let a=state.listings.filter(l=>{const u=userFor(l.id);if(!$('showHidden').checked&&u.hidden)return false;if($('favoritesOnly').checked&&!u.favorite)return false;if(l.status==='removed'&&!$('showHidden').checked)return false;if((l.sqft||0)<minSqft||(l.bedrooms||0)<beds||(l.bathrooms||0)<baths)return false;if(l.rent<minPrice||l.rent>maxPrice)return false;if(minYear&&(l.buildingYear||0)<minYear)return false;if($('acOnly').checked&&l.ac!==true)return false;if($('parkingOnly').checked&&l.parking!==true)return false;if($('purposeOnly').checked&&l.type!=='purpose-built')return false;if($('hideNorth').checked&&['n','north'].includes((l.orientation||'').toLowerCase()))return false;return true});const sort=$('sortBy').value;a.sort((x,y)=>sort==='priceAsc'?x.rent-y.rent:sort==='priceDesc'?y.rent-x.rent:sort==='sqftDesc'?(y.sqft||0)-(x.sqft||0):sort==='newest'?new Date(y.firstSeen)-new Date(x.firstSeen):score(y).value-score(x).value);return a;}
function badges(l){let b=[];if(l.status==='new')b.push('<span class="badge new">NEW</span>');if(l.priceDrop)b.push('<span class="badge drop">PRICE DROP</span>');if(l.status==='removed')b.push('<span class="badge removed">REMOVED</span>');b.push(`<span class="badge">${l.type==='purpose-built'?'PURPOSE-BUILT':'CONDO / PRIVATE'}</span>`);return b.join('');}
function chips(l){const items=[[l.ac===true?'AC':l.ac===false?'No AC':'AC ? ',l.ac===true?'good':l.ac===false?'warn':''],[l.parking===true?'Parking':l.parking===false?'No parking':'Parking ? ',l.parking===true?'good':''],[l.petFriendly===true?'Pet friendly':l.petFriendly===false?'No pets':'Pets ? ',l.petFriendly===true?'good':''],[l.orientation?`${l.orientation} facing`:'Facing ? ',['S','SE','SW','South','Southeast','Southwest'].includes(l.orientation)?'good':['N','North'].includes(l.orientation)?'warn':''],[l.balcony===true?'Balcony':l.balcony===false?'No balcony':'Balcony ? ',l.balcony===true?'good':''],[l.buildingYear?`Built ${l.buildingYear}`:'Year ? ','']];return items.map(([t,c])=>`<span class="chip ${c}">${t}</span>`).join('');}
function render(){const data=filtered();$('resultCount').textContent=data.length;const root=$('listings');root.innerHTML='';for(const l of data){const u=userFor(l.id),sc=score(l),node=$('listingTemplate').content.cloneNode(true),card=node.querySelector('.listing-card');card.dataset.id=l.id;node.querySelector('.badges').innerHTML=badges(l);node.querySelector('.score').textContent=`${sc.value}% match`;node.querySelector('.title').textContent=[l.buildingName,l.unit].filter(Boolean).join(' · ')||l.address;node.querySelector('.address').textContent=`${l.address} · ${l.neighborhood}`;node.querySelector('.rent').textContent=`${money(l.rent)} / mo`;node.querySelector('.effective').textContent=l.effectiveRent&&l.effectiveRent!==l.rent?`${money(l.effectiveRent)} effective`:'';node.querySelector('.facts').innerHTML=`<span>${l.bedrooms ?? '?'} BR</span><span>${l.bathrooms ?? '?'} BA</span><span>${l.sqft?l.sqft.toLocaleString()+' sqft':'sqft ?'}</span><span>${l.sqft?money(Math.round(l.rent/l.sqft))+'/sqft':'$/sqft ?'}</span>`;node.querySelector('.chips').innerHTML=chips(l);node.querySelector('.why').textContent=sc.reasons.length?`Match: ${sc.reasons.join(' · ')}`:'Limited preference data available.';const hist=(state.history[l.id]||[]);node.querySelector('.history-body').innerHTML=hist.length?hist.map(h=>`${h.date}: ${money(h.rent)}${h.note?' — '+h.note:''}`).join('<br>'):'No earlier observations yet.';const fav=node.querySelector('[data-action="favorite"]'),contact=node.querySelector('[data-action="contacted"]'),hidden=node.querySelector('[data-action="hidden"]');fav.classList.toggle('active',u.favorite);fav.textContent=u.favorite?'♥ Favorite':'♡ Favorite';contact.classList.toggle('active',u.contacted);hidden.classList.toggle('active',u.hidden);for(const btn of [fav,contact,hidden])btn.onclick=()=>{const key=btn.dataset.action==='favorite'?'favorite':btn.dataset.action==='hidden'?'hidden':'contacted';u[key]=!u[key];saveUser();render();};const link=node.querySelector('.source-link');link.href=l.url;link.textContent=`${l.source} ↗`;const notes=node.querySelector('.notes');notes.value=u.notes||'';notes.onchange=()=>{u.notes=notes.value;saveUser();};node.querySelector('.meta').textContent=`Last checked ${l.lastChecked}${l.dataNotes?' · '+l.dataNotes:''}`;card.onmouseenter=()=>highlight(l.id,true);card.onmouseleave=()=>highlight(l.id,false);root.appendChild(node);}renderMarkers(data);renderStats();}
function renderStats(){const active=state.listings.filter(x=>x.status!=='removed'),fresh=active.filter(x=>x.status==='new'),drops=active.filter(x=>x.priceDrop);$('stats').innerHTML=`<div class="stat"><strong>${active.length}</strong><span>Active</span></div><div class="stat"><strong>${fresh.length}</strong><span>New</span></div><div class="stat"><strong>${drops.length}</strong><span>Price drops</span></div><div class="stat"><strong>${state.meta?.lastRefreshed?.slice(0,10)||'—'}</strong><span>Last refreshed</span></div>`;}
function initMap(){state.map=L.map('map',{zoomControl:true}).setView([49.263,-123.166],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);}
function renderMarkers(data){for(const m of state.markers.values())m.remove();state.markers.clear();for(const l of data){if(!l.lat||!l.lng)continue;const icon=L.divIcon({className:`price-marker ${l.type==='purpose-built'?'':'condo'} ${l.status==='removed'?'removed':''}`,html:`<div>${money(l.rent).replace('CA','')}</div>`,iconSize:[70,28],iconAnchor:[35,14]});const m=L.marker([l.lat,l.lng],{icon}).addTo(state.map);m.bindPopup(`<strong>${l.buildingName||l.address}</strong><br>${l.bedrooms}BR · ${l.sqft||'?'} sqft<br>${money(l.rent)}/mo`);m.on('click',()=>document.querySelector(`[data-id="${CSS.escape(l.id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}));state.markers.set(l.id,m);}}
function highlight(id,on){const m=state.markers.get(id);if(m&&on)m.openPopup();if(m&&!on)m.closePopup();}
async function init(){initMap();const [lr,hr]=await Promise.all([fetch('data/listings.json'),fetch('data/history.json')]);const payload=await lr.json();state.listings=payload.listings;state.meta=payload.meta;state.history=await hr.json();document.querySelectorAll('.toolbar input,.toolbar select,#sortBy').forEach(el=>el.addEventListener('change',render));$('resetFilters').onclick=()=>{$('minSqft').value=0;$('beds').value=0;$('baths').value=0;$('minPrice').value='';$('maxPrice').value='';$('minYear').value='';['acOnly','parkingOnly','hideNorth','purposeOnly','favoritesOnly','showHidden'].forEach(id=>$(id).checked=false);render();};render();}
init().catch(err=>{$('listings').innerHTML=`<p>Could not load listing data: ${err.message}</p>`;console.error(err);});
