const USER_STATE_KEY='vancouver-rentals:user-state:v1';

const VERIFIED_IMAGES={
  'arbutus-residences-315-2den-900':[
    'https://rf-images-prod-bcdn.rentfaster.ca/454186/17802679.v.c07ac6fe3caaac1790c1a84fecc9fdb5.jpg',
    'https://rf-images-prod-bcdn.rentfaster.ca/454186/slide_13677345.v.1af4d567e873b5f269da1b72896b5d8e.jpg',
    'https://rf-images-prod-bcdn.rentfaster.ca/454186/slide_15043243.v.eaa24c66594e0084c7d13305525c4add.jpg'
  ],
  'arbutus-terrace-unit6-2den':[
    'https://cms.stranddev.com/uploads/_1200x800_crop_center-center_100_line/Arbutus-Dusk.png',
    'https://cms.stranddev.com/uploads/_1800x1012_crop_center-center_100_line/7-web-or-mls-007_2026-04-13-185215_hhvb.jpg',
    'https://assets.rentsync.com/strand/images/gallery/1152/1783029799015_ChatGPT_Image_Jun_29__2026__03_05_33_PM.png'
  ],
  'treo-2688-vine-r3142696':[
    'https://photos.zolo.ca/2688-vine-vancouver-R3142696-1-p480.jpg?2026-07-08+22%3A50%3A09=',
    'https://photos.zolo.ca/2688-vine-vancouver-R3142696-2-p480.jpg?2026-07-08+22%3A50%3A10='
  ],
  'blenheim-terrace-204-r3149612':[
    'https://photos.zolo.ca/204-3333-west-4th-avenue-vancouver-R3149612-1-p480.jpg?2026-08-05+19%3A25%3A02=',
    'https://photos.zolo.ca/204-3333-west-4th-avenue-vancouver-R3149612-2-p480.jpg?2026-08-05+19%3A25%3A03='
  ],
  'york-103-2535-r3137446':[
    'https://iss-cdn.myrealpage.com/JJoTxvFUAtG7KxCK79uD8Mze_I1Rh9gZkPhlOY9SkAM/rs%3Aauto%3A0%3A0%3A0/g%3Asm/aHR0cDovL3MzLmFtYXpvbmF3cy5jb20vbXJwLWxpc3RpbmdzLzcvOS8yLzEwOTA5NDI5Ny8zYjFkYTdiZjk1NDljYWFlNWU4OTA5ZjE2MmM2MGYzOS5qcGVn',
    'https://iss-cdn.myrealpage.com/Da5OArdZ0YlHgEGM04vZcBR03s9IhTbcWuQoUwHJFKU/rs%3Aauto%3A320%3A0%3A0/g%3Asm/aHR0cDovL3MzLmFtYXpvbmF3cy5jb20vbXJwLWxpc3RpbmdzLzcvOS8yLzEwOTA5NDI5Ny8zYjFkYTdiZjk1NDljYWFlNWU4OTA5ZjE2MmM2MGYzOS5qcGVn',
    'https://iss-cdn.myrealpage.com/7mdxK8SGlhQCNpIRqP8KB5vHL5qdkBpnd2yeb2l_Z_M/rs%3Aauto%3A320%3A0%3A0/g%3Asm/aHR0cDovL3MzLmFtYXpvbmF3cy5jb20vbXJwLWxpc3RpbmdzLzcvOS8yLzEwOTA5NDI5Ny81Y2E1OWRhYmI1MjdjMzUzNWJhZDY1ZDVkYWU3ZDY5MC5qcGVn'
  ],
  'solo-2228-marstrand':[
    'https://static.wixstatic.com/media/cd8db0_40239115f34843c5877c2624bc2d34d7~mv2.jpg/v1/fill/w_938%2Ch_635%2Cq_90%2Cenc_avif%2Cquality_auto/cd8db0_40239115f34843c5877c2624bc2d34d7~mv2.jpg',
    'https://static.wixstatic.com/media/cd8db0_76521ec1095a4332a06c933b84ba93f7~mv2.jpg/v1/fill/w_675%2Ch_635%2Cq_90%2Cenc_avif%2Cquality_auto/cd8db0_76521ec1095a4332a06c933b84ba93f7~mv2.jpg',
    'https://static.wixstatic.com/media/cd8db0_6ef0a5c58ff04abd843038e89b22999b~mv2.jpg/v1/fill/w_675%2Ch_635%2Cq_90%2Cenc_avif%2Cquality_auto/cd8db0_6ef0a5c58ff04abd843038e89b22999b~mv2.jpg'
  ]
};

const state={listings:[],history:{},user:JSON.parse(localStorage.getItem(USER_STATE_KEY)||'{}'),markers:new Map(),map:null,meta:{}};
const $=id=>document.getElementById(id);
const money=n=>n==null?'—':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(n);
const availability=l=>l.availabilityStatus||(l.status==='removed'?'removed':'active');
function saveUser(){localStorage.setItem(USER_STATE_KEY,JSON.stringify(state.user));}
function userFor(id){return state.user[id]||(state.user[id]={favorite:false,hidden:false,contacted:false,notes:''});}
function imagesFor(l){const own=Array.isArray(l.images)?l.images.filter(Boolean):[];return [...new Set(own.length?own:(VERIFIED_IMAGES[l.id]||[]))];}
function photoSourceUrl(l){return l.photoPageUrl||l.url||'#';}
function photoLabel(l){return l.photoCount?`View ${l.photoCount} photos on source ↗`:'View photos on source ↗';}

function score(l){let s=0,reasons=[];if(l.sqft>=800){s+=18;reasons.push('800+ sqft')}if(l.bedrooms>=2){s+=15;reasons.push('2BR+')}if(l.bathrooms>=2)s+=8;if(l.ac===true){s+=16;reasons.push('AC')}else if(l.ac===false)s-=10;if(l.buildingYear>=2020){s+=12;reasons.push('newer building')}else if(l.buildingYear>=2015)s+=7;const o=(l.orientation||'').toLowerCase();if(['s','south','se','southeast','sw','southwest'].includes(o)){s+=12;reasons.push('preferred exposure')}if(['n','north'].includes(o)){s-=18;reasons.push('north-facing')}if(l.parking===true){s+=7;reasons.push('parking')}if(l.largeWindows===true){s+=6;reasons.push('large windows')}if(l.modernInterior===true){s+=6;reasons.push('modern interior')}if(l.type==='purpose-built')s+=3;return {value:Math.max(0,Math.min(100,Math.round(s))),reasons};}

function filtered(){const minSqft=+$('minSqft').value||0,beds=+$('beds').value||0,baths=+$('baths').value||0,minPrice=+$('minPrice').value||0,maxPrice=+$('maxPrice').value||Infinity,minYear=+$('minYear').value||0;let a=state.listings.filter(l=>{const u=userFor(l.id),av=availability(l);if(!$('showHidden').checked&&(u.hidden||av!=='active'))return false;if($('favoritesOnly').checked&&!u.favorite)return false;if((l.sqft||0)<minSqft||(l.bedrooms||0)<beds||(l.bathrooms||0)<baths)return false;if(l.rent<minPrice||l.rent>maxPrice)return false;if(minYear&&(l.buildingYear||0)<minYear)return false;if($('acOnly').checked&&l.ac!==true)return false;if($('parkingOnly').checked&&l.parking!==true)return false;if($('purposeOnly').checked&&l.type!=='purpose-built')return false;if($('hideNorth').checked&&['n','north'].includes((l.orientation||'').toLowerCase()))return false;return true});const sort=$('sortBy').value;a.sort((x,y)=>sort==='priceAsc'?x.rent-y.rent:sort==='priceDesc'?y.rent-x.rent:sort==='sqftDesc'?(y.sqft||0)-(x.sqft||0):sort==='newest'?new Date(y.firstSeen)-new Date(x.firstSeen):score(y).value-score(x).value);return a;}

function badges(l){let b=[],av=availability(l);if(av==='active'&&l.status==='new')b.push('<span class="badge new">NEW</span>');if(av==='active'&&(l.status==='price_drop'||l.priceDrop))b.push('<span class="badge drop">PRICE DROP</span>');if(av==='removed')b.push('<span class="badge removed">REMOVED</span>');if(av==='needs_confirmation')b.push('<span class="badge drop">VERIFY</span>');if(l.status==='corrected'&&av==='active')b.push('<span class="badge">CORRECTED</span>');b.push(`<span class="badge">${l.type==='purpose-built'?'PURPOSE-BUILT':'CONDO / PRIVATE'}</span>`);return b.join('');}
function chips(l){const items=[[l.ac===true?'AC':l.ac===false?'No AC':'AC ?',l.ac===true?'good':l.ac===false?'warn':''],[l.parking===true?'Parking':l.parking===false?'No parking':'Parking ?',l.parking===true?'good':''],[l.petFriendly===true?'Pet friendly':l.petFriendly===false?'No pets':'Pets ?',l.petFriendly===true?'good':''],[l.orientation?`${l.orientation} facing`:'Facing ?',['S','SE','SW','South','Southeast','Southwest'].includes(l.orientation)?'good':['N','North'].includes(l.orientation)?'warn':''],[l.balcony===true?'Balcony':l.balcony===false?'No balcony':'Balcony ?',l.balcony===true?'good':''],[l.buildingYear?`Built ${l.buildingYear}`:'Year ?','']];return items.map(([t,c])=>`<span class="chip ${c}">${t}</span>`).join('');}

function fallbackPhotoMarkup(l,message='Photos are available on the original listing'){return `<div class="photo-placeholder photo-fallback"><strong>${l.buildingName||'Rental listing'}</strong><span>${message}</span><a class="photo-source-link" href="${photoSourceUrl(l)}" target="_blank" rel="noopener noreferrer">${photoLabel(l)}</a></div>`;}
function photoMarkup(l){const images=imagesFor(l);if(!images.length)return `<div class="photo-wrap">${fallbackPhotoMarkup(l)}</div>`;return `<div class="photo-wrap" data-photo-index="0"><img class="listing-photo" src="${images[0]}" alt="${l.buildingName||l.address}" loading="lazy"><div class="photo-nav">${images.length>1?'<button class="photo-prev" type="button" aria-label="Previous photo">‹</button><button class="photo-next" type="button" aria-label="Next photo">›</button>':''}<span class="photo-count">1 / ${images.length}</span></div></div>`;}
function wirePhotos(card,l){const wrap=card.querySelector('.photo-wrap'),images=imagesFor(l);if(!wrap||!images.length)return;const img=wrap.querySelector('.listing-photo'),count=wrap.querySelector('.photo-count'),nav=wrap.querySelector('.photo-nav');const failed=new Set();let current=0;const show=i=>{current=(i+images.length)%images.length;wrap.dataset.photoIndex=current;img.style.display='block';img.src=images[current];if(count)count.textContent=`${current+1} / ${images.length}`;};const showFallback=()=>{img.style.display='none';if(nav)nav.style.display='none';if(!wrap.querySelector('.photo-fallback'))wrap.insertAdjacentHTML('afterbegin',fallbackPhotoMarkup(l,'Embedded photos could not be loaded'));};const tryNextWorking=()=>{failed.add(current);if(failed.size>=images.length){showFallback();return;}for(let step=1;step<=images.length;step++){const next=(current+step)%images.length;if(!failed.has(next)){show(next);return;}}showFallback();};wrap.querySelector('.photo-prev')?.addEventListener('click',e=>{e.stopPropagation();show(current-1)});wrap.querySelector('.photo-next')?.addEventListener('click',e=>{e.stopPropagation();show(current+1)});img.addEventListener('error',tryNextWorking);}

function render(){const data=filtered();$('resultCount').textContent=data.length;updateFilterCount();const root=$('listings');root.innerHTML='';for(const l of data){const u=userFor(l.id),sc=score(l),node=$('listingTemplate').content.cloneNode(true),card=node.querySelector('.listing-card');card.dataset.id=l.id;const body=document.createElement('div');body.className='listing-body';while(card.firstChild)body.appendChild(card.firstChild);card.appendChild(document.createRange().createContextualFragment(photoMarkup(l)));card.appendChild(body);node.querySelector('.badges').innerHTML=badges(l);node.querySelector('.score').textContent=`${sc.value}% match`;node.querySelector('.title').textContent=[l.buildingName,l.unit].filter(Boolean).join(' · ')||l.address;node.querySelector('.address').textContent=`${l.address} · ${l.neighborhood}`;node.querySelector('.rent').textContent=`${money(l.rent)} / mo`;node.querySelector('.effective').textContent=l.effectiveRent&&l.effectiveRent!==l.rent?`${money(l.effectiveRent)} effective`:'';node.querySelector('.facts').innerHTML=`<span>${l.bedrooms ?? '?'} BR</span><span>${l.bathrooms ?? '?'} BA</span><span>${l.sqft?l.sqft.toLocaleString()+' sqft':'sqft ?'}</span><span>${l.sqft?money(Math.round(l.rent/l.sqft))+'/sqft':'$/sqft ?'}</span>`;node.querySelector('.chips').innerHTML=chips(l);node.querySelector('.why').textContent=availability(l)==='active'?(sc.reasons.length?`Match: ${sc.reasons.join(' · ')}`:'Limited preference data available.'):`Verification: ${l.verificationMethod||'not currently verified'}`;const hist=state.history[l.id]||[];node.querySelector('.history-body').innerHTML=hist.length?hist.map(h=>`${h.date}: ${h.rent==null?'—':money(h.rent)}${h.note?' — '+h.note:''}`).join('<br>'):'No earlier observations yet.';const fav=node.querySelector('[data-action="favorite"]'),contact=node.querySelector('[data-action="contacted"]'),hidden=node.querySelector('[data-action="hidden"]');fav.classList.toggle('active',u.favorite);fav.textContent=u.favorite?'♥ Favorite':'♡ Favorite';contact.classList.toggle('active',u.contacted);hidden.classList.toggle('active',u.hidden);for(const btn of [fav,contact,hidden])btn.onclick=()=>{const key=btn.dataset.action==='favorite'?'favorite':btn.dataset.action==='hidden'?'hidden':'contacted';u[key]=!u[key];saveUser();render();};const link=node.querySelector('.source-link');link.href=l.url;link.textContent=`${l.source} ↗`;const notes=node.querySelector('.notes');notes.value=u.notes||'';notes.onchange=()=>{u.notes=notes.value;saveUser();};node.querySelector('.meta').textContent=`Last checked ${l.lastChecked||'—'}${l.verifiedAt?' · verified '+l.verifiedAt.replace('T',' ').slice(0,16):''}${l.dataNotes?' · '+l.dataNotes:''}`;card.onmouseenter=()=>highlight(l.id,true);card.onmouseleave=()=>highlight(l.id,false);root.appendChild(node);wirePhotos(root.lastElementChild,l);}renderMarkers(data);renderStats();}
function renderStats(){const active=state.listings.filter(x=>availability(x)==='active'),fresh=active.filter(x=>x.status==='new'),drops=active.filter(x=>x.status==='price_drop'||x.priceDrop),verify=state.listings.filter(x=>availability(x)==='needs_confirmation');$('stats').innerHTML=`<div class="stat"><strong>${active.length}</strong><span>Active</span></div><div class="stat"><strong>${fresh.length}</strong><span>New</span></div><div class="stat"><strong>${drops.length}</strong><span>Price drops</span></div><div class="stat"><strong>${verify.length}</strong><span>To verify</span></div><div class="stat"><strong>${state.meta?.lastRefreshed?.slice(0,10)||'—'}</strong><span>Last refreshed</span></div>`;}
function updateFilterCount(){let n=0;if((+$('minSqft').value||0)>0)n++;if((+$('beds').value||0)>0)n++;if((+$('baths').value||0)>0)n++;if($('minPrice').value)n++;if($('maxPrice').value)n++;if($('minYear').value)n++;['acOnly','parkingOnly','hideNorth','purposeOnly','favoritesOnly','showHidden'].forEach(id=>{if($(id).checked)n++;});$('filterCount').textContent=n?`(${n})`:'';}
function initMap(){state.map=L.map('map',{zoomControl:true}).setView([49.263,-123.166],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);}
function renderMarkers(data){for(const m of state.markers.values())m.remove();state.markers.clear();for(const l of data){if(!l.lat||!l.lng)continue;const av=availability(l),icon=L.divIcon({className:`price-marker ${l.type==='purpose-built'?'':'condo'} ${av!=='active'?'removed':''}`,html:`<div>${money(l.rent).replace('CA','')}</div>`,iconSize:[70,28],iconAnchor:[35,14]});const m=L.marker([l.lat,l.lng],{icon}).addTo(state.map);m.bindPopup(`<strong>${l.buildingName||l.address}</strong><br>${l.unit||''} ${l.bedrooms}BR · ${l.sqft||'?'} sqft<br>${money(l.rent)}/mo`);m.on('click',()=>{if(window.innerWidth<=900)setView('list');setTimeout(()=>document.querySelector(`[data-id="${CSS.escape(l.id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)});state.markers.set(l.id,m);}}
function highlight(id,on){const m=state.markers.get(id);if(m&&on)m.openPopup();if(m&&!on)m.closePopup();}
function setView(view){const layout=document.querySelector('.layout'),mapMode=view==='map';layout.classList.toggle('map-mode',mapMode);$('mapView').classList.toggle('active',mapMode);$('listView').classList.toggle('active',!mapMode);if(mapMode)setTimeout(()=>state.map.invalidateSize(),80);}
async function jsonFresh(path){const sep=path.includes('?')?'&':'?';const r=await fetch(`${path}${sep}t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json();}
async function init(){initMap();const [payload,history]=await Promise.all([jsonFresh('data/listings.json'),jsonFresh('data/history.json')]);state.listings=payload.listings;state.meta=payload.meta||{};state.history=history;document.querySelectorAll('.toolbar input,.toolbar select,#sortBy').forEach(el=>el.addEventListener('change',render));$('filtersToggle').onclick=()=>{const t=$('toolbar'),open=t.classList.toggle('mobile-open');$('filtersToggle').setAttribute('aria-expanded',open);};$('listView').onclick=()=>setView('list');$('mapView').onclick=()=>setView('map');$('resetFilters').onclick=()=>{$('minSqft').value=0;$('beds').value=0;$('baths').value=0;$('minPrice').value='';$('maxPrice').value='';$('minYear').value='';['acOnly','parkingOnly','hideNorth','purposeOnly','favoritesOnly','showHidden'].forEach(id=>$(id).checked=false);render();};render();}
init().catch(err=>{$('listings').innerHTML=`<p>Could not load listing data: ${err.message}</p>`;console.error(err);});
